name: "Create Release"

on:
  pull_request:
    branches:
      - master
    types:
      - opened
    paths:
      - src/**
      - android/**
      - ios/**

jobs:
  upgrade-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Config
        run: |
          git config --local user.email ${{ secrets.USER_EMAIL }}
          git config --local user.name ${{ secrets.USER_NAME }}
      - name: "Install dependecies"
        run: yarn install

      - name: Update app version
        run: yarn update-version

      - name: Push versions
        run: |
          git fetch
          git checkout master
          git commit -m "Update app version" -a
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.USER_NAME }}

  create-draft-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: New release draft
          release_name: New release draft
          draft: true
          prerelease: false
