name: "google play deploy"

on:
  push:
    branches: [feat/automate-deploy]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" > release.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD }}" --batch release.asc > android/app/release.keystore
      - name: Build aab
        run: |
          yarn install
          [ -d android/app/main/assets ] || mkdir android/app/main/assets
          yarn build:aab
