name: "Google Play Deploy"

on:
  release:
    types: [published]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Rebuild keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" > release.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD }}" --batch release.asc > android/app/release.keystore

      - name: Build dotenv
        run: yarn build-dotenv

      - name: Build aab
        run: |
          [ -d android/app/src/main/assets ] || mkdir android/app/src/main/assets
          yarn release:aab

      - name: Deploy to store
        run: yarn deploy:android
        env:
          GAPI_EMAIL: ${{ secrets.GAPI_EMAIL }}
          GAPI_KEY: ${{ secrets.GAPI_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
